services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: distribuidora-api
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
      db-migrator:
        condition: service_completed_successfully
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_SERVER=sqlserver
      - DB_PORT=1433
      - DB_NAME=distribuidora_db
      - DB_USER=SA
      - DB_PASSWORD=yourStrongPassword123#
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - distribuidora-network
    volumes:
      - ./backend/api/app/uploads:/app/uploads   # persistir uploads entre reinicios y hacerlo accesible desde contenedor

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: distribuidora-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
      db-migrator:
        condition: service_completed_successfully
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SMTP_HOST=email-smtp.<region>.amazonaws.com
      - SMTP_PORT=587
      - SMTP_USER=AKIA4LK5VLMNEWTDJQVS
      - SMTP_PASS=BHmouW5kBsfS7VtHFpk78UzcevCMFfSScvrBUWNHPHTP
      - DB_SERVER=sqlserver
      - DB_PORT=1433
      - DB_NAME=distribuidora_db
      - DB_USER=SA
      - DB_PASSWORD=yourStrongPassword123#
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - distribuidora-network

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - distribuidora-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword123#
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - sqlserver_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'yourStrongPassword123#' -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s
    restart: unless-stopped
    networks:
      - distribuidora-network

  db-migrator:
    image: mcr.microsoft.com/mssql-tools # This image contains sqlcmd
    container_name: distribuidora-db-migrator
    restart: "no"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Mount the entire sql directory
    command: /bin/bash /docker-entrypoint-initdb.d/init-db.sh
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - distribuidora-network

volumes:
  sqlserver_data:

networks:
  distribuidora-network:
    driver: bridge